CREATE TABLE recruit.jobs(
    company VARCHAR(20) DEFAULT '',
    department VARCHAR(255) DEFAULT '',
    NAME VARCHAR(255) DEFAULT '',
    category1 INT DEFAULT 0,
    category2 VARCHAR(255) DEFAULT '',
    degree VARCHAR(20) DEFAULT '',
    base VARCHAR(20) DEFAULT '',
    experience INT DEFAULT 0,
    origin_id VARCHAR(128) DEFAULT '',
    origin_url VARCHAR(512) DEFAULT '',
    requirement TEXT,
    description TEXT,
    open_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    close_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    is_urgent INT DEFAULT 0,
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    modify_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    UNIQUE com_job_id(company, origin_id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
